#!/bin/sh
echo -e 127.0.0.1 $SWARMIT_INGRESS_DOMAINS >> /etc/hosts
for d in $SWARMIT_INGRESS_DOMAINS
do
echo CERT-$d /usr/lib/nagios/plugins/check_http -H $d -C 60,30 >> /etc/check_mk/mrpe.cfg
done
for u in $$SWARMIT_INGRESS_URLS
do
ADD=""
n=$(echo $u | sed -e 's#https://##')
p=$(echo $n | sed -e 's#/# -u /#')
n=$(echo $n | sed -e 's#/.*##')
if [[ ! -z p ]]
then
ADD=${p}
fi
if [[ ! -z u ]]
then
if [[ ! -z ADD ]]
then
echo URL-$u /usr/lib/nagios/plugins/check_http -ssl -H ${ADD} -C 60,30 >> /etc/check_mk/mrpe.cfg
else
echo URL-$u /usr/lib/nagios/plugins/check_http -ssl -H $n -C 60,30 >> /etc/check_mk/mrpe.cfg
fi
fi
done